[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/data/recognizedCustomers.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
